### ISSUE TITLE
the real length of encoder length

### ISSUE THREAD

**Issue by ShengleiH** [jingxil/Pointer-Networks#3]
Hello, I have another question and hope you could help me out.

In the model part, from line 109 to line 125:

```
...  other codes ...

# Shape: [batch_size, max_input_sequence_len + 1, 2]
encoder_inputs = tf.stack(encoder_inputs, axis=0)

...  other codes ...

# Encode input to obtain memory for later queries
memory, _ = tf.nn.bidirectional_dynamic_rnn(fw_enc_cell, bw_enc_cell, encoder_inputs, enc_input_lens, dtype=tf.float32)

...  other codes ...
```

If I understand it correctly, encoder inputs should include END token, therefore the real length of the encoder inputs now should be `enc_input_lens + 1` and 1 is for END. 

Then why the `enc_input_lens` doesn't change in this code?

Thank you :) @jingxil

**Comment by jingxil** [comment]
Hi, I caught a glimpse of the code and it is a typo. The output length is added by 1 not the input length. Because we add the `<begin>` and `<end>`  tokens to the output.  For the decoder the input is like  `<begin> ... original sequence ...` and the target is like ` ... original sequence ... <end>` . Hope it helps :)
